/* This file is automagically generated by build. Do NOT edit. */

#define VERSION_BUILD  67
#define VERSION_USER   "lundman"
#define VERSION_HOST   "shinken.local"
#define VERSION_DATE   "Tue Mar  6 10:01:23 2018"
#define VERSION_STRING "lundman@shinken.local build 67 (Tue Mar  6 10:01:23 2018)"

/* Lundtastic services */
