/* This file is automagically generated by build. Do NOT edit. */

#define VERSION_BUILD  64
#define VERSION_USER   "lundman"
#define VERSION_HOST   "shinken.local"
#define VERSION_DATE   "Fri Sep 22 09:39:04 2017"
#define VERSION_STRING "lundman@shinken.local build 64 (Fri Sep 22 09:39:04 2017)"

/* Lundtastic services */
