/* This file is automagically generated by build. Do NOT edit. */

#define VERSION_BUILD  1546
#define VERSION_USER   "lundman"
#define VERSION_HOST   "shinken.interq.or.jp"
#define VERSION_DATE   "Wed Aug 29 11:38:55 2012"
#define VERSION_STRING "lundman@shinken.interq.or.jp build 1546 (Wed Aug 29 11:38:55 2012)"

/* Lundtastic services */
