/* This file is automagically generated by build. Do NOT edit. */

#define VERSION_BUILD  167
#define VERSION_USER   "lundman"
#define VERSION_HOST   "netbsd.interq.or.jp"
#define VERSION_DATE   "Sun Aug 20 09:09:24 2006"
#define VERSION_STRING "lundman@netbsd.interq.or.jp build 167 (Sun Aug 20 09:09:24 2006)"

/* Lundtastic services */
